#define IDC_CheckboxTNT L"CheckboxTNT"
#define IDC_CheckboxFireSpreads L"CheckboxFireSpreads"
#define IDC_ButtonTeleportToPlayer L"ButtonTeleportToPlayer"
#define IDC_ButtonTeleportPlayerToMe L"ButtonTeleportPlayerToMe"
#define IDC_GameOptions L"GameOptions"
#define IDC_InGameHostOptions L"InGameHostOptions"
